name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@f1ff1cf13a2143e1e04a55da4b1fd77c2adb9b78 # v14.0.0
