name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@3cd2608174c02a8a3f23f8fb490f60446cd88aca # v12.10.2
