name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  actions-ci:
    uses: alextheman231/github-actions/.github/workflows/actions-ci.yml@1463f1cd916d9a2ada1f257dd7eaa5bda546b886 # v12.9.2
